-- 010_research_memory.sql
-- Adaptive web-reference memory for current technical guidance and UI/UX inspiration.
--
-- Apply this migration after 009_atomic_file_locks.sql.
-- It is REQUIRED for cross-session/project research memory, but the live web-research tool
-- remains functional without it because persistence is intentionally best-effort.

CREATE TABLE IF NOT EXISTS public.research_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  project_id uuid REFERENCES public.projects(id) ON DELETE CASCADE,
  query text NOT NULL,
  mode text NOT NULL CHECK (mode IN ('current-tech', 'ui-ux', 'deep')),
  summary text NOT NULL,
  palette text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.research_sources (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id uuid NOT NULL REFERENCES public.research_runs(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  project_id uuid REFERENCES public.projects(id) ON DELETE CASCADE,
  title text NOT NULL,
  uri text NOT NULL,
  domain text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.research_patterns (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id uuid NOT NULL REFERENCES public.research_runs(id) ON DELETE CASCADE,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  project_id uuid REFERENCES public.projects(id) ON DELETE CASCADE,
  pattern text NOT NULL,
  evidence text NOT NULL,
  applicability text NOT NULL,
  novelty text NOT NULL CHECK (novelty IN ('low', 'medium', 'high')),
  is_global_candidate boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS research_runs_project_created_idx
  ON public.research_runs(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS research_patterns_global_idx
  ON public.research_patterns(is_global_candidate, novelty, created_at DESC);
CREATE INDEX IF NOT EXISTS research_sources_domain_idx
  ON public.research_sources(domain);

ALTER TABLE public.research_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.research_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.research_patterns ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Research runs owner read" ON public.research_runs;
CREATE POLICY "Research runs owner read"
  ON public.research_runs FOR SELECT TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Research runs owner insert" ON public.research_runs;
CREATE POLICY "Research runs owner insert"
  ON public.research_runs FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Research sources owner read" ON public.research_sources;
CREATE POLICY "Research sources owner read"
  ON public.research_sources FOR SELECT TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Research sources owner insert" ON public.research_sources;
CREATE POLICY "Research sources owner insert"
  ON public.research_sources FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "Research patterns owner read" ON public.research_patterns;
CREATE POLICY "Research patterns owner read"
  ON public.research_patterns FOR SELECT TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Research patterns owner insert" ON public.research_patterns;
CREATE POLICY "Research patterns owner insert"
  ON public.research_patterns FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());


-- Research memory is user-owned. Allow correction/deletion of bad or stale findings
-- without allowing one account to mutate another account's research history.
create policy "research_runs_update_own" on public.research_runs
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "research_runs_delete_own" on public.research_runs
  for delete using (user_id = auth.uid());
create policy "research_sources_update_own" on public.research_sources
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "research_sources_delete_own" on public.research_sources
  for delete using (user_id = auth.uid());
create policy "research_patterns_update_own" on public.research_patterns
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "research_patterns_delete_own" on public.research_patterns
  for delete using (user_id = auth.uid());
